PromoBundle_homepage:
    pattern:  /
    defaults: { _controller: "PromoBundle:Static:index" }
    requirements:
        _method:  GET

PromoBundle_empresa:
    pattern:  /empresa
    defaults: { _controller: "PromoBundle:Static:empresa" }
    requirements:
        _method:  GET

PromoBundle_consultoria:
    pattern:  /consultoria
    defaults: { _controller: "PromoBundle:Static:consultoria" }
    requirements:
        _method:  GET

PromoBundle_casosexito:
    pattern:  /casosexito
    defaults: { _controller: "PromoBundle:Static:casosexito" }
    requirements:
        _method:  GET

PromoBundle_contacto:
    pattern:  /contacto
    defaults: { _controller: "PromoBundle:Static:contacto" }
    requirements:
        _method:  GET

PromoBundle_catalogo:
    pattern:  /catalogo/{categoria}
    defaults: { _controller: "PromoBundle:Productes:catalogo", categoria: "0-lista_categorias" }
    requirements:
        _method:  GET

PromoBundle_categoria:
    pattern:  /admin/categoria
    defaults: { _controller: "PromoBundle:Admin:categoria" }
    requirements:
        _method:  GET|POST

PromoBundle_producto:
    pattern:  /admin/producto
    defaults: { _controller: "PromoBundle:Admin:producto" }
    requirements:
        _method:  GET|POST


PromoBundle_login:
    pattern:  /admin/login
    defaults: { _controller: "PromoBundle:Security:login" }
    requirements:
        _method:  GET|POST
        