PromoBundle_homepage:
    pattern:  /
    defaults: { _controller: "PromoBundle:Static:index" }
    requirements:
        _method:  GET

PromoBundle_empresa:
    pattern:  /empresa
    defaults: { _controller: "PromoBundle:Static:empresa" }
    requirements:
        _method:  GET

PromoBundle_consultoria:
    pattern:  /consultoria
    defaults: { _controller: "PromoBundle:Static:consultoria" }
    requirements:
        _method:  GET

PromoBundle_contacto:
    pattern:  /contacto
    defaults: { _controller: "PromoBundle:Static:contacto" }
    requirements:
        _method:  GET

PromoBundle_catalogo:
    pattern:  /catalogo/{categoria}
    defaults: { _controller: "PromoBundle:Productes:catalogo", categoria: "0-lista_categorias" }
    requirements:
        _method:  GET

PromoBundle_catalogodetalle:
    pattern:  /catalogo/producto/{producto}
    defaults: { _controller: "PromoBundle:Productes:producto" }
    requirements:
        _method:  GET

PromoBundle_casosexito:
    pattern:  /casosexito
    defaults: { _controller: "PromoBundle:Productes:casosexito" }
    requirements:
        _method:  GET

PromoBundle_admin:
    pattern:  /admin
    defaults: { _controller: "PromoBundle:Admin:login" }
    requirements:
        _method:  GET|POST

PromoBundle_login:
    pattern:  /admin/login
    defaults: { _controller: "PromoBundle:Admin:login" }
    requirements:
        _method:  GET|POST

PromoBundle_logout:
    pattern:  /admin/logout
    defaults: { _controller: "PromoBundle:Admin:logout" }
    requirements:
        _method:  GET

PromoBundle_usuari:
    pattern:  /admin/usuario
    defaults: { _controller: "PromoBundle:Admin:usuari" }
    requirements:
        _method:  GET|POST

PromoBundle_categoria:
    pattern:  /admin/categoria
    defaults: { _controller: "PromoBundle:Admin:categoria" }
    requirements:
        _method:  GET|POST

PromoBundle_removecategoria:
    pattern:  /admin/removecategoria
    defaults: { _controller: "PromoBundle:Admin:removecategoria" }
    requirements:
        _method:  GET

PromoBundle_producto:
    pattern:  /admin/producto
    defaults: { _controller: "PromoBundle:Admin:producto" }
    requirements:
        _method:  GET|POST

PromoBundle_portada:
    pattern:  /admin/portada
    defaults: { _controller: "PromoBundle:Admin:portada" }
    requirements:
        _method:  GET

PromoBundle_borrarimagen:
    pattern:  /admin/borrarimagen 
    defaults: { _controller: "PromoBundle:Admin:borrarimagen" }
    requirements:
        _method:  GET

PromoBundle_removeproducto:
    pattern:  /admin/removeproducto
    defaults: { _controller: "PromoBundle:Admin:removeproducto" }
    requirements:
        _method:  GET


PromoBundle_galeria:
    pattern:  /admin/galeria
    defaults: { _controller: "PromoBundle:Admin:galeria" }
    requirements:
        _method:  GET|POST


        